apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: keda-http-add-on
  namespace: flux-system
spec:
  interval: 10m
  releaseName: keda-http-add-on
  targetNamespace: keda
  chart:
    spec:
      chart: keda-add-ons-http
      version: 0.8.0
      sourceRef:
        kind: HelmRepository
        name: kedacore
        namespace: flux-system
  dependsOn:
    - name: keda
  install:
    createNamespace: false
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    images:
      operator: ghcr.io/kedacore/http-add-on-operator
      scaler: ghcr.io/kedacore/http-add-on-scaler
      interceptor: ghcr.io/kedacore/http-add-on-interceptor
      tag: 0.8.0
      kubeRbacProxy:
        name: gcr.io/kubebuilder/kube-rbac-proxy
        tag: v0.13.0
